excuses = [
    'Ai sanoit että sen EI kuulu tapahtua?',
    'Asiakas on varmaan hakkeroitu.',
    'Datassasi on varmaan jotain outoa.',
    'En kirjoittanut sitä osaa ohjelmasta.',
    'En löytänyt netistä yhtään ohjetta miten se tehdään.',
    'En löytänyt yhtään kirjastoa joka osaisi tehdä sen.',
    'En ole ehtinyt ajamaan sitä koodia vielä.',
    'En ole koskenut siihen koodiin viikkoihin.',
    'En ole onnistunut toistamaan sitä.',
    'En ole varma,'
    'En olettanut että teen virheitä.',
    'En saanut siitä tikettiä.',
    'En varmaankaan ymmärtänyt mitä halusit.',
    'En voi testata kaikkea.',
    'Et voi käyttää tuota versiota järjestelmässäsi.',
    'jota ei ollut.',
    'joten jouduin olettamaan miten se pitäisi tehdä.',
    'Kaikki näyttää hyvältä täällä päässä.',
    'Kolmannen osapuolen dokumentaatio puuttuu.',
    'Koodia käännetään.',
    'koska en ole vielä katsonut miten se toimii.',
    'koska meillä oli vain kuukausi aikaa koodata se.',
    'Kukaan ei kertonut,'
    'Kukaan ei kysynyt kauanko siinä oikeasti menee.',
    'Kukaan ei ole koskaan valittanut siitä.',
    'Kuulin että tänään oli auringonpurkaus.',
    'Käytimme kolme kuukautta sen debuggaukseen,'
    'Käyttäjä ei varmaankaan osaa käyttää sitä.',
    'Käytät sitä väärin.',
    'Lataus on varmaan korruptoitunut.',
    'Luulin että hyväksyit sen?',
    'Luulin että hän ymmärtää kontekstista mitä tarkoitan.',
    'Luulin että sain sen valmiiksi.',
    'Markkinointiosasto käski pistämään sen siihen.',
    'Meidän olisi pitänyt päivittää tämä vuosia sitten.',
    'Meillä ei ollut tarpeeksi aikaa vertaisarvioida sitä.',
    'Miksi haluat tehdä sen noin?',
    'miltä se tuntuu?',
    'Minulla on liikaa korkeamman prioriteetin juttuja juuri nyt.',
    'Minun täytyy korjata se joskus myöhemmin.',
    'Missä olit kun tämä levisi reisille?',
    'Mitä kirjoitit väärin että sait sen rikki?',
    'mutta korjaus ei ole vielä päivittynyt.',
    'No mutta ainakin se näyttää kauniin virheilmoituksen.',
    'No nyt ainakin tiedetään olla kokeilematta sitä uudestaan.',
    'Nykyinen toteutus tekee siitä vaikean tehdä oikein.',
    'Olen yllättynyt että se toimii noinkin hyvin.',
    'Ongelma näyttää olevan legacy-softassa.',
    'Projektipäällikkö käski tekemään sen noin.',
    'Projektipäällikkö sanoi ettemme koskaan tarvitse sitä ominaisuutta.',
    'Rauta on liian hidas.',
    'Rikoin sen tahallani testatakseni yhtä juttua.',
    'Saan yleensä notifikaation kun se tapahtuu.',
    'Sanoin jo eilen että se on valmis päivän loppuun mennessä.',
    'se arvo on väärässä vain puolet ajasta.',
    'Se ei ole bugi,'
    'Se ei ole koskaan aiemmin toiminut noin ennalta-arvaamattomasti.',
    'Se ei olisi taloudellisesti järkevää.',
    'Se ei voi olla rikki,'
    'Se johtuu varmaankin karkausvuodesta.',
    'se läpäisee kaikki yksikkötestit.',
    'Se oli vain väliaikainen korjaus.',
    'Se ominaisuus oli suunniteltu vaiheeseen kaksi.',
    'Se on aina ollut noin.',
    'Se on graafikon vika.',
    'Se on itse asiassa ominaisuus.',
    'Se on jo korjattu,'
    'Se on merkistöongelma.',
    'Se on ongelma kolmannen osapuolen koodissa.',
    'Se on tunnettu bugi tässä ohjelmointikielessä.',
    'se on virhe asetuksissa.',
    'Se prosessi vaatii ihmisen tekemää valvontaa,'
    'Se toimi eilen.',
    'Se toimi päässäni.',
    'Se toimi täydellisesti kun kirjoitin sen.',
    'Se toimii minulla.',
    'Se toiminnallisuus ei kuulu vaatimusmäärittelyyn.',
    'Se tuskin tapahtuu uudestaan.',
    'Se virhe oli kirjaimellisesti yksi mijoonassa.',
    'Se virhe tarkoittaa että se onnistui.'
    'Selaimesi välimuistissa on varmaan vanhaa koodia.',
    'Sen koodin kirjoitti edellinen kaveri.',
    'Sen täytyy olla rautaongelma.',
    'Sinulla on varmaankin väärä versio.',
    'Sinulta puuttuu varmaankin jotain paketteja.',
    'Sitä tietoa ei ole koskaan kerätty.',
    'Teen sitä juuri parhaillaan.',
    'Tehokkuussyistä tarkastan tämän sähköpostilaatikon vain perjantaisin.',
    'Tuota en ole nähnyt eläissäni.',
    'Tämä ei kuulu työnkuvaani.',
    'Tämä on tiedossa oleva bugi johon kielsit koskemasta vielä.',
    'Tämän koodin ei kuulunut vielä olla tuotannossa.',
    'Unohdin kommitoida koodin joka korjaa tuon.',
    'Vaikkei se toimikaan,'
    'Vika ei ole koodissa - käyttäjä tarvitsee lisää koulutusta.',
    'WYSIWYG tuotti varmaan väärää koodia.',
    'Yksikkötestit eivät kata sitä mahdollisuutta.',
    'Älä huoli,'
]
